import type { SipocNode, SipocEdge } from '../types/sipoc.types';

export const demoNodes: SipocNode[] = [
  {
    id: 'node-1',
    type: 'sipoc',
    position: { x: 50, y: 250 },
    data: {
      label: 'Receive Claim',
      processDescription: 'Customer submits insurance claim via online portal, mobile app, or call center. Initial documentation and photos are collected.',
      suppliers: 'Policyholder\nInsurance Broker\nCall Center Agent',
      inputs: 'Claim Form\nPolicy Number\nIncident Documentation\nPhotographic Evidence',
      outputs: 'Registered Claim\nClaim Reference Number',
      customers: 'Claims Processing Team',
      applicationsInvolved: 'Guidewire ClaimCenter\nCustomer Self-Service Portal\nAWS S3 (Document Storage)',
      involvedTeams: 'Customer Service\nFirst Notice of Loss (FNOL) Team',
      knownIssues: 'Mobile app uploads sometimes fail for large files\nCall center agents occasionally miss required fields',
    },
  },
  {
    id: 'node-2',
    type: 'sipoc',
    position: { x: 350, y: 250 },
    data: {
      label: 'Validate Claim',
      processDescription: 'Verify policy coverage, check claim eligibility, and validate submitted documentation for completeness.',
      suppliers: 'Claims Processing Team',
      inputs: 'Registered Claim\nPolicy Database Record\nCoverage Terms',
      outputs: 'Validated Claim\nCoverage Confirmation',
      customers: 'Fraud Detection Team\nClaims Adjuster',
      applicationsInvolved: 'Guidewire ClaimCenter\nPolicy Administration System\nDocument Management (OpenText)',
      involvedTeams: 'Claims Processing Team\nUnderwriting Support',
      knownIssues: 'Policy database sync delays cause false "not covered" flags\nManual override needed for legacy policies migrated from old system',
    },
  },
  {
    id: 'node-3',
    type: 'sipoc',
    position: { x: 650, y: 100 },
    data: {
      label: 'Fraud Screening',
      processDescription: 'Run automated fraud detection algorithms and flag suspicious claims for manual review. Cross-reference with industry databases.',
      suppliers: 'Claims Processing Team\nExternal Fraud Databases',
      inputs: 'Validated Claim\nHistorical Claim Patterns\nIndustry Watch Lists',
      outputs: 'Fraud Risk Score\nScreening Report',
      customers: 'Claims Adjuster\nSpecial Investigations Unit',
      applicationsInvolved: 'FRISS Fraud Detection\nLexisNexis Risk Solutions\nInternal ML Model (Python/SageMaker)',
      involvedTeams: 'Fraud Detection Team\nData Science Team',
      knownIssues: 'ML model has 12% false positive rate on water damage claims\nLexisNexis API occasionally times out during batch processing',
    },
  },
  {
    id: 'node-4',
    type: 'sipoc',
    position: { x: 650, y: 400 },
    data: {
      label: 'Assign Adjuster',
      processDescription: 'Route claim to appropriate claims adjuster based on claim type, complexity, value, and adjuster workload/expertise.',
      suppliers: 'Claims Processing Team',
      inputs: 'Validated Claim\nAdjuster Availability Matrix\nClaim Complexity Score',
      outputs: 'Assigned Claim\nAdjuster Assignment Notification',
      customers: 'Claims Adjuster',
      applicationsInvolved: 'Guidewire ClaimCenter\nWorkforce Management System\nMicrosoft Teams (Notifications)',
      involvedTeams: 'Claims Operations\nResource Management',
      knownIssues: 'Workload balancing algorithm does not account for adjuster PTO\nHigh-value claims sometimes assigned to junior adjusters during peak periods',
    },
  },
  {
    id: 'node-5',
    type: 'sipoc',
    position: { x: 950, y: 250 },
    data: {
      label: 'Investigate Claim',
      processDescription: 'Adjuster reviews all documentation, contacts involved parties, may arrange site visits or request additional evidence. Determines loss amount.',
      suppliers: 'Claims Adjuster\nThird-Party Assessors',
      inputs: 'Assigned Claim\nFraud Risk Score\nScreening Report\nPolicy Terms',
      outputs: 'Investigation Report\nLoss Assessment\nSettlement Recommendation',
      customers: 'Settlement Approval Team',
      applicationsInvolved: 'Guidewire ClaimCenter\nXactimate (Damage Estimation)\nGoogle Maps\nMobile Inspection App',
      involvedTeams: 'Claims Adjusters\nField Inspectors\nThird-Party Assessors',
      knownIssues: 'Field inspection scheduling averages 5-day wait time\nXactimate pricing database not updated for recent material cost increases',
    },
  },
  {
    id: 'node-6',
    type: 'sipoc',
    position: { x: 1250, y: 150 },
    data: {
      label: 'Approve Settlement',
      processDescription: 'Review settlement recommendation against policy limits and authority levels. Senior approval required for claims above threshold.',
      suppliers: 'Settlement Approval Team\nClaims Manager',
      inputs: 'Investigation Report\nSettlement Recommendation\nPolicy Limits\nAuthority Matrix',
      outputs: 'Approved Settlement Amount\nApproval Documentation',
      customers: 'Payment Processing Team',
      applicationsInvolved: 'Guidewire ClaimCenter\nApproval Workflow Engine\nSAP Finance (Budget Check)',
      involvedTeams: 'Claims Management\nActuarial Team (for large claims)',
      knownIssues: 'Claims above €50k require 3 approvals — average 2-day delay per approval level\nNo weekend coverage for senior approvers',
    },
  },
  {
    id: 'node-7',
    type: 'sipoc',
    position: { x: 1250, y: 380 },
    data: {
      label: 'Reject or Dispute',
      processDescription: 'Issue formal rejection notice with detailed reasoning. Handle customer disputes, escalations, and ombudsman referrals.',
      suppliers: 'Claims Adjuster\nLegal Team',
      inputs: 'Investigation Report\nPolicy Exclusions\nRejection Criteria',
      outputs: 'Rejection Notice\nDispute Resolution Outcome',
      customers: 'Policyholder\nCompliance Department',
      applicationsInvolved: 'Guidewire ClaimCenter\nDocument Generation (DocuSign)\nComplaints Management System',
      involvedTeams: 'Claims Management\nLegal Team\nCustomer Complaints',
      knownIssues: 'Rejection letter templates not updated for new regulation (IDD)\n15% of rejections escalate to ombudsman',
    },
  },
  {
    id: 'node-8',
    type: 'sipoc',
    position: { x: 1550, y: 150 },
    data: {
      label: 'Process Payment',
      processDescription: 'Execute approved settlement payment to policyholder or directly to repair service provider. Handle tax withholding if applicable.',
      suppliers: 'Payment Processing Team\nFinance Department',
      inputs: 'Approved Settlement Amount\nBeneficiary Bank Details\nTax Information',
      outputs: 'Payment Confirmation\nPayment Reference\nRemittance Advice',
      customers: 'Policyholder\nRepair Service Provider',
      applicationsInvolved: 'SAP Finance\nBank Payment Gateway (SWIFT)\nGuidewire BillingCenter',
      involvedTeams: 'Finance Department\nTreasury Operations',
      knownIssues: 'International payments take 3-5 business days\nSWIFT cut-off time (14:00) causes next-day delays for late approvals',
    },
  },
  {
    id: 'node-9',
    type: 'sipoc',
    position: { x: 1850, y: 250 },
    data: {
      label: 'Close Claim',
      processDescription: 'Finalize all documentation, archive records, update claim status. Trigger customer satisfaction survey and recovery/subrogation if applicable.',
      suppliers: 'Claims Processing Team\nFinance Department',
      inputs: 'Payment Confirmation\nAll Claim Documentation\nRecovery Assessment',
      outputs: 'Closed Claim Record\nCustomer Satisfaction Survey\nRecovery Referral (if applicable)',
      customers: 'Policyholder\nActuarial Department\nRecovery Team',
      applicationsInvolved: 'Guidewire ClaimCenter\nSurveyMonkey\nDocument Archive (AWS S3)\nBI Reporting (Power BI)',
      involvedTeams: 'Claims Processing Team\nCustomer Experience Team',
      knownIssues: 'Survey response rate only 18%\nArchiving large claims (100+ documents) sometimes exceeds S3 upload timeout',
    },
  },
  {
    id: 'node-10',
    type: 'sipoc',
    position: { x: 2150, y: 250 },
    data: {
      label: 'Reporting & Analytics',
      processDescription: 'Aggregate claim data for management reporting, regulatory compliance (Solvency II), and continuous process improvement analysis.',
      suppliers: 'Claims Processing Team\nData Warehouse',
      inputs: 'Closed Claim Record\nHistorical Claim Data\nKPI Targets',
      outputs: 'Claims Dashboard\nRegulatory Reports\nProcess Improvement Recommendations',
      customers: 'Claims Director\nCompliance Officer\nBoard of Directors',
      applicationsInvolved: 'Power BI\nSnowflake Data Warehouse\nSolvency II Reporting Tool\nJira (Improvement Backlog)',
      involvedTeams: 'Business Intelligence Team\nCompliance Department\nContinuous Improvement',
      knownIssues: 'Data warehouse refresh runs nightly — no real-time reporting\nSolvency II report generation takes 4 hours during quarter-end',
    },
  },
];

export const demoEdges: SipocEdge[] = [
  { id: 'e1-2', source: 'node-1', target: 'node-2', type: 'smart', animated: true, data: { label: 'Registered Claim' } },
  { id: 'e2-3', source: 'node-2', target: 'node-3', type: 'smart', animated: true, data: { label: 'Validated Claim' } },
  { id: 'e2-4', source: 'node-2', target: 'node-4', type: 'smart', animated: true, data: { label: 'Validated Claim' } },
  { id: 'e3-5', source: 'node-3', target: 'node-5', type: 'smart', animated: true, data: { label: 'Fraud Risk Score' } },
  { id: 'e4-5', source: 'node-4', target: 'node-5', type: 'smart', animated: true, data: { label: 'Assigned Claim' } },
  { id: 'e5-6', source: 'node-5', target: 'node-6', type: 'smart', animated: true, data: { label: 'Settlement Recommendation' } },
  { id: 'e5-7', source: 'node-5', target: 'node-7', type: 'smart', animated: true, data: { label: 'Rejection Recommendation' } },
  { id: 'e6-8', source: 'node-6', target: 'node-8', type: 'smart', animated: true, data: { label: 'Approved Settlement' } },
  { id: 'e8-9', source: 'node-8', target: 'node-9', type: 'smart', animated: true, data: { label: 'Payment Confirmation' } },
  { id: 'e7-9', source: 'node-7', target: 'node-9', type: 'smart', animated: true, data: { label: 'Dispute Resolution Outcome' } },
  { id: 'e9-10', source: 'node-9', target: 'node-10', type: 'smart', animated: true, data: { label: 'Closed Claim Record' } },
];
